In [ ]:
import random
def route_distance(route, distances):
    total_distance = 0
    for i in range(len(route) - 1):  # Iterate through city pairs
        city1, city2 = route[i], route[i + 1]
        distance = distances.get((city1, city2), distances.get((city2, city1), float('inf')))
        if distance == float('inf'):
            print(f"Warning: No distance found between {city1} and {city2}")
        total_distance += distance
    return total_distance

# Fitness function: inversely proportional to route distance
def fitness(route, distances):
    total_distance = route_distance(route, distances)
    return 1 / total_distance if total_distance > 0 else float('inf')

# Initialize a population of random routes
def initialize_population(cities, population_size, start_city=None):
    population = []
    for _ in range(population_size):
        route = cities[:]
        if start_city:
            route.remove(start_city)  # Remove the starting city
            random.shuffle(route)
            route = [start_city] + route + [start_city]  # Add start city at beginning and end
        else:
            random.shuffle(route)
            route.append(route[0])  # Close the loop for non-fixed start
        population.append(route)
    return population

# Roulette-wheel selection based on fitness
def selection(population, distances):
    fitness_scores = [fitness(route, distances) for route in population]
    total_fitness = sum(fitness_scores)
    if total_fitness == 0:  # Prevent division by zero
        return random.sample(population, 2)
    probabilities = [score / total_fitness for score in fitness_scores]
    return random.choices(population, weights=probabilities, k=2)

def crossover(parent1, parent2):
    # Select a random crossover point
    crossover_point = random.randint(1, len(parent1) - 2)  # Exclude the start and end cities
    # Take the 2 segments from both parents
    first_segment = parent1[:crossover_point]
    second_segment = parent2[crossover_point:-1]  # Exclude the final city of parent2

    child = first_segment + second_segment
    # Validate for duplicates and missing cities
    if len(set(child)) == len(parent1) - 1:  # Ensure all unique cities are present
        child.append(child[0])  # Close the loop by appending the start city
        return child
    else:
        # Return None if the child is invalid
        return None

# Mutation by swapping two cities in the middle of the route
def mutate(route, mutation_rate):
    if random.random() < mutation_rate:
        i, j = random.sample(range(1, len(route) - 1), 2)  # Exclude start and end cities
        route[i], route[j] = route[j], route[i]
    return route

# Generate the next generation of the population
def next_generation(population, distances, mutation_rate):
    new_population = []
    for _ in range(len(population)):
        parent1, parent2 = select_parents(population, distances)
        child = crossover(parent1, parent2)
        child = mutate(child, mutation_rate)
        new_population.append(child)
    return new_population

# Genetic Algorithm
def genetic_algorithm(cities, distances, population_size, mutation_rate, max_generations, start_city=None, verbose=True):
    # Validate the starting city if provided
    if start_city and start_city not in cities:
        raise ValueError(f"Starting city '{start_city}' is not in the list of cities: {cities}")
    population = initialize_population(cities, population_size, start_city)
    for generation in range(1, max_generations + 1):
        if verbose:
            print(f"Generation: {generation}")
        # Calculate fitness for the current population
        fitness_population = [(route, fitness(route, distances)) for route in population]
        fitness_population = sorted(fitness_population, key=lambda x: x[1], reverse=True)
        # Preserve the top 10% (elite individuals)
        elite_count = max(1, population_size // 10)
        elites = [route for route, _ in fitness_population[:elite_count]]
        # Print the best route and its fitness if verbose is True
        best_route, best_fitness = fitness_population[0]
        if verbose:
            print(f"Best Route: {' -> '.join(best_route)} Distance: {1 / best_fitness:.2f}")
        selected_population = selection([route for route, _ in fitness_population], distances)
        # Generate new population
        new_population = elites[:]  # add elites
        max_attempts = 100  # To prevent infinite loops
        attempts = 0
        while len(new_population) < population_size and attempts < max_attempts:
            parent1, parent2 = random.sample(selected_population, 2)
            child = crossover(parent1, parent2)
            if child:  # Only accept valid children
                child = mutate(child, mutation_rate)
                new_population.append(child)
            attempts += 1
        # If max_attempts is reached
        if len(new_population) < population_size:
            if verbose:
                print(f"Warning: max_attempts reached. Population not fully regenerated. "
                      f"Created {len(new_population)} individuals out of {population_size}.")
            missing_count = population_size - len(new_population)
            if verbose:
                print(f"Filling {missing_count} missing individuals with random routes.")
            for _ in range(missing_count):
                random_route = cities[:]
                random.shuffle(random_route)
                if start_city:
                    random_route = [start_city] + [city for city in random_route if city != start_city] + [start_city]
                else:
                    random_route.append(random_route[0])  # Close the loop
                new_population.append(random_route)
        # Replace the old population with the new generation
        population = new_population
    best_route, best_fitness = sorted([(route, fitness(route, distances)) for route in population], key=lambda x: x[1], reverse=True)[0]
    return best_route, 1 / best_fitness

In [ ]:
# TravOrder Data
distances = {
    ('B', 'L'): 3,
    ('L', 'M'): 4.5,
    ('M', 'S'): 3.1,
    ('S', 'L'): 5.7,
    ('B', 'M'): 7.6,
    ('B', 'S'): 7.8
}

      # Boston, London, Mumbai, Shanghai
cities = ['B', 'L', 'M', 'S']

population_size = 100
mutation_rate = 0.2
max_generations = 10

best_route, best_distance = genetic_algorithm(cities, distances, population_size, mutation_rate, max_generations,start_city = 'B')

print("\nBest Route Found:", " -> ".join(best_route))
print(f"Best Distance: {best_distance:.2f}")

Generation: 1
Best Route: B -> L -> M -> S -> B Distance: 18.40
Generation: 2
Best Route: B -> L -> M -> S -> B Distance: 18.40
Warning: max_attempts reached. Population not fully regenerated. Created 40 individuals out of 100.
Filling 60 missing individuals with random routes.
Generation: 3
Best Route: B -> L -> M -> S -> B Distance: 18.40
Warning: max_attempts reached. Population not fully regenerated. Created 79 individuals out of 100.
Filling 21 missing individuals with random routes.
Generation: 4
Best Route: B -> L -> M -> S -> B Distance: 18.40
Generation: 5
Best Route: B -> L -> M -> S -> B Distance: 18.40
Generation: 6
Best Route: B -> L -> M -> S -> B Distance: 18.40
Generation: 7
Best Route: B -> L -> M -> S -> B Distance: 18.40
Generation: 8
Best Route: B -> L -> M -> S -> B Distance: 18.40
Warning: max_attempts reached. Population not fully regenerated. Created 71 individuals out of 100.
Filling 29 missing individuals with random routes.
Generation: 9
Best Route: B -> L -> M -> S -> B Distance: 18.40
Warning: max_attempts reached. Population not fully regenerated. Created 73 individuals out of 100.
Filling 27 missing individuals with random routes.
Generation: 10
Best Route: B -> L -> M -> S -> B Distance: 18.40
Warning: max_attempts reached. Population not fully regenerated. Created 78 individuals out of 100.
Filling 22 missing individuals with random routes.

Best Route Found: B -> L -> M -> S -> B
Best Distance: 18.40

In [ ]:
distances = {
    ('B', 'L'): 3,
    ('L', 'M'): 4.5,
    ('M', 'S'): 3.1,
    ('S', 'L'): 5.7,
    ('B', 'M'): 7.6,
    ('B', 'S'): 7.8
}

      # Boston, London, Mumbai, Shanghai
cities = ['B', 'L', 'M', 'S']

population_size = 100
mutation_rate = 0.2
max_generations = 10

for i in range(10):
  best_route, best_distance = genetic_algorithm(cities, distances, population_size, mutation_rate, max_generations,start_city = 'B', verbose= False)
  print(f'Run {i+1}')
  print("Best Route Found:", " -> ".join(best_route))
  print(f"Best Distance: {best_distance:.2f}\n")

Run 1
Best Route Found: B -> S -> M -> L -> B
Best Distance: 18.40

Run 2
Best Route Found: B -> L -> M -> S -> B
Best Distance: 18.40

Run 3
Best Route Found: B -> S -> M -> L -> B
Best Distance: 18.40

Run 4
Best Route Found: B -> S -> M -> L -> B
Best Distance: 18.40

Run 5
Best Route Found: B -> L -> M -> S -> B
Best Distance: 18.40

Run 6
Best Route Found: B -> S -> M -> L -> B
Best Distance: 18.40

Run 7
Best Route Found: B -> S -> M -> L -> B
Best Distance: 18.40

Run 8
Best Route Found: B -> L -> M -> S -> B
Best Distance: 18.40

Run 9
Best Route Found: B -> S -> M -> L -> B
Best Distance: 18.40

Run 10
Best Route Found: B -> S -> M -> L -> B
Best Distance: 18.40

In [ ]:
# Illusrative Data

cities = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']
# Generate random distances between the cities
def generate_pairwise_distances(cities, low=5, high=100, median=20, seed=None):
    if seed:
        random.seed(seed)  # For reproducibility
    distances = {}
    for i, city1 in enumerate(cities):
        for j, city2 in enumerate(cities):
            if i < j:  # Avoid duplicates and self-distances
                # Generate random distance using a normal distribution around the median
                random_distance = random.gauss(median, median / 2)  # Standard deviation = median / 2
                random_distance = max(low, min(random_distance, high))  # Clamp between low and high
                distances[(city1, city2)] = round(random_distance, 2)
    return distances

distances = generate_pairwise_distances(cities, low=5, high=100, seed=42)

distances

{('A', 'B'): 18.56,
 ('A', 'C'): 18.27,
 ('A', 'D'): 18.89,
 ('A', 'E'): 27.02,
 ('A', 'F'): 18.72,
 ('A', 'G'): 5.03,
 ('A', 'H'): 23.32,
 ('A', 'I'): 17.33,
 ('A', 'J'): 17.83,
 ('B', 'C'): 21.16,
 ('B', 'D'): 22.32,
 ('B', 'E'): 31.64,
 ('B', 'F'): 26.57,
 ('B', 'G'): 21.11,
 ('B', 'H'): 12.62,
 ('B', 'I'): 9.85,
 ('B', 'J'): 22.46,
 ('C', 'D'): 33.11,
 ('C', 'E'): 20.42,
 ('C', 'F'): 18.94,
 ('C', 'G'): 25.32,
 ('C', 'H'): 5.46,
 ('C', 'I'): 16.88,
 ('C', 'J'): 24.9,
 ('D', 'E'): 28.73,
 ('D', 'F'): 17.59,
 ('D', 'G'): 23.77,
 ('D', 'H'): 22.48,
 ('D', 'I'): 27.82,
 ('D', 'J'): 8.87,
 ('E', 'F'): 25.68,
 ('E', 'G'): 5,
 ('E', 'H'): 5,
 ('E', 'I'): 13.93,
 ('E', 'J'): 10.84,
 ('F', 'G'): 28.76,
 ('F', 'H'): 26.64,
 ('F', 'I'): 7.81,
 ('F', 'J'): 28.47,
 ('G', 'H'): 9.98,
 ('G', 'I'): 19.14,
 ('G', 'J'): 17.06,
 ('H', 'I'): 21.14,
 ('H', 'J'): 28.19,
 ('I', 'J'): 26.38}

In [ ]:
population_size = 100
mutation_rate = 0.2
max_generations = 10

best_route, best_distance = genetic_algorithm(cities, distances, population_size, mutation_rate, max_generations,start_city = 'A')

print("\nBest Route Found:", " -> ".join(best_route))
print(f"Best Distance: {best_distance:.2f}")

Generation: 1
Best Route: A -> G -> J -> E -> H -> C -> B -> D -> I -> F -> A Distance: 141.22
Warning: max_attempts reached. Population not fully regenerated. Created 22 individuals out of 100.
Filling 78 missing individuals with random routes.
Generation: 2
Best Route: A -> G -> J -> E -> H -> C -> B -> D -> I -> F -> A Distance: 141.22
Warning: max_attempts reached. Population not fully regenerated. Created 20 individuals out of 100.
Filling 80 missing individuals with random routes.
Generation: 3
Best Route: A -> G -> J -> E -> H -> C -> B -> D -> I -> F -> A Distance: 141.22
Warning: max_attempts reached. Population not fully regenerated. Created 20 individuals out of 100.
Filling 80 missing individuals with random routes.
Generation: 4
Best Route: A -> G -> B -> I -> F -> C -> H -> D -> J -> E -> A Distance: 137.41
Warning: max_attempts reached. Population not fully regenerated. Created 23 individuals out of 100.
Filling 77 missing individuals with random routes.
Generation: 5
Best Route: A -> G -> B -> I -> F -> C -> H -> D -> J -> E -> A Distance: 137.41
Warning: max_attempts reached. Population not fully regenerated. Created 33 individuals out of 100.
Filling 67 missing individuals with random routes.
Generation: 6
Best Route: A -> G -> E -> H -> C -> I -> F -> B -> J -> D -> A Distance: 121.97
Warning: max_attempts reached. Population not fully regenerated. Created 52 individuals out of 100.
Filling 48 missing individuals with random routes.
Generation: 7
Best Route: A -> G -> E -> J -> D -> F -> I -> H -> C -> B -> A Distance: 121.46
Warning: max_attempts reached. Population not fully regenerated. Created 16 individuals out of 100.
Filling 84 missing individuals with random routes.
Generation: 8
Best Route: A -> G -> E -> J -> D -> F -> I -> H -> C -> B -> A Distance: 121.46
Warning: max_attempts reached. Population not fully regenerated. Created 21 individuals out of 100.
Filling 79 missing individuals with random routes.
Generation: 9
Best Route: A -> G -> E -> J -> D -> F -> I -> H -> C -> B -> A Distance: 121.46
Warning: max_attempts reached. Population not fully regenerated. Created 21 individuals out of 100.
Filling 79 missing individuals with random routes.
Generation: 10
Best Route: A -> G -> E -> J -> D -> F -> I -> H -> C -> B -> A Distance: 121.46
Warning: max_attempts reached. Population not fully regenerated. Created 20 individuals out of 100.
Filling 80 missing individuals with random routes.

Best Route Found: A -> G -> E -> J -> D -> F -> I -> H -> C -> B -> A
Best Distance: 121.46

In [ ]:
population_size = 100
mutation_rate = 0.2
max_generations = 10

for i in range(10):
  best_route, best_distance = genetic_algorithm(cities, distances, population_size, mutation_rate, max_generations,start_city = 'A', verbose= False)
  print(f'Run {i+1}')
  print("Best Route Found:", " -> ".join(best_route))
  print(f"Best Distance: {best_distance:.2f}\n")

Run 1
Best Route Found: A -> C -> B -> H -> E -> I -> F -> D -> J -> G -> A
Best Distance: 127.34

Run 2
Best Route Found: A -> G -> H -> E -> J -> D -> F -> C -> I -> B -> A
Best Distance: 121.54

Run 3
Best Route Found: A -> F -> I -> C -> B -> D -> J -> E -> H -> G -> A
Best Distance: 126.61

Run 4
Best Route Found: A -> I -> F -> C -> H -> E -> J -> D -> B -> G -> A
Best Distance: 122.71

Run 5
Best Route Found: A -> C -> H -> E -> G -> J -> D -> B -> I -> F -> A
Best Distance: 118.36

Run 6
Best Route Found: A -> F -> I -> B -> C -> H -> E -> G -> D -> J -> A
Best Distance: 123.47

Run 7
Best Route Found: A -> F -> I -> C -> H -> B -> J -> D -> E -> G -> A
Best Distance: 131.58

Run 8
Best Route Found: A -> F -> C -> H -> B -> I -> E -> J -> D -> G -> A
Best Distance: 128.03

Run 9
Best Route Found: A -> B -> D -> J -> F -> I -> C -> H -> E -> G -> A
Best Distance: 123.40

Run 10
Best Route Found: A -> I -> F -> D -> J -> G -> E -> H -> C -> B -> A
Best Distance: 123.84

In [ ]:
# tuning 1: increase generations
population_size = 100
mutation_rate = 0.2
max_generations = 100

result = []
for i in range(100):
  best_route, best_distance = genetic_algorithm(cities, distances, population_size, mutation_rate, max_generations,start_city = 'A', verbose= False)
  result.append( best_distance)

df = pd.DataFrame(result)
df.describe()

               0
count  100.00000
mean   110.22880
std      5.10982
min    101.34000
25%    106.11000
50%    111.80000
75%    114.14750
max    121.43000

In [ ]:
# tuning 1: increase generations
population_size = 100
mutation_rate = 0.2
max_generations = 200

result = []
for i in range(100):
  best_route, best_distance = genetic_algorithm(cities, distances, population_size, mutation_rate, max_generations,start_city = 'A', verbose= False)
  result.append( best_distance)

df = pd.DataFrame(result)
df.describe()

                0
count  100.000000
mean   107.504600
std      4.845822
min    101.340000
25%    103.600000
50%    108.070000
75%    112.230000
max    119.050000

In [ ]:
# tuning 2: increase population
population_size = 200
mutation_rate = 0.2
max_generations = 200

result = []
for i in range(100):
  best_route, best_distance = genetic_algorithm(cities, distances, population_size, mutation_rate, max_generations,start_city = 'A', verbose= False)
  result.append( best_distance)

df = pd.DataFrame(result)
df.describe()

                0
count  100.000000
mean   105.593400
std      4.094404
min    101.340000
25%    101.340000
50%    103.600000
75%    108.070000
max    114.860000

In [ ]:
# tuning 2: increase population
population_size = 400
mutation_rate = 0.2
max_generations = 200

result = []
for i in range(100):
  best_route, best_distance = genetic_algorithm(cities, distances, population_size, mutation_rate, max_generations,start_city = 'A', verbose= False)
  result.append( best_distance)

df = pd.DataFrame(result)
df.describe()

                0
count  100.000000
mean   104.037600
std      3.036434
min    101.340000
25%    101.340000
50%    103.600000
75%    106.110000
max    112.230000

In [ ]:
# tuning 2: increase mutation rate
population_size = 400
mutation_rate = 0.3
max_generations = 200

result = []
for i in range(100):
  best_route, best_distance = genetic_algorithm(cities, distances, population_size, mutation_rate, max_generations,start_city = 'A', verbose= False)
  result.append( best_distance)

df = pd.DataFrame(result)
df.describe()

                0
count  100.000000
mean   104.013400
std      2.940613
min    101.340000
25%    101.340000
50%    103.600000
75%    106.110000
max    111.800000

## PyGAD Implementation

In [ ]:
import random
import numpy as np
from deap import base, creator, tools, algorithms

# Distance matrix as a NumPy array
distance_matrix = np.array([
    [0, 18.56, 18.27, 18.89, 27.02, 18.72, 5.03, 23.32, 17.33, 17.83],
    [18.56, 0, 21.16, 22.32, 31.64, 26.57, 21.11, 12.62, 9.85, 22.46],
    [18.27, 21.16, 0, 33.11, 20.42, 18.94, 25.32, 5.46, 16.88, 24.9],
    [18.89, 22.32, 33.11, 0, 28.73, 17.59, 23.77, 22.48, 27.82, 8.87],
    [27.02, 31.64, 20.42, 28.73, 0, 25.68, 5, 5, 13.93, 10.84],
    [18.72, 26.57, 18.94, 17.59, 25.68, 0, 28.76, 26.64, 7.81, 28.47],
    [5.03, 21.11, 25.32, 23.77, 5, 28.76, 0, 9.98, 19.14, 17.06],
    [23.32, 12.62, 5.46, 22.48, 5, 26.64, 9.98, 0, 21.14, 28.19],
    [17.33, 9.85, 16.88, 27.82, 13.93, 7.81, 19.14, 21.14, 0, 26.38],
    [17.83, 22.46, 24.9, 8.87, 10.84, 28.47, 17.06, 28.19, 26.38, 0]
])

# Number of cities
num_cities = len(distance_matrix)

# Create the fitness function and individual class
creator.create("FitnessMin", base.Fitness, weights=(-1.0,))
creator.create("Individual", list, fitness=creator.FitnessMin)

# Initialize the toolbox
toolbox = base.Toolbox()

# Attribute generator: random permutation of cities
toolbox.register("indices", random.sample, range(num_cities), num_cities)

# Structure initializers
toolbox.register("individual", tools.initIterate, creator.Individual, toolbox.indices)
toolbox.register("population", tools.initRepeat, list, toolbox.individual)

# Evaluation function
def evalTSP(individual):
    distance = 0
    for i in range(num_cities):
        distance += distance_matrix[individual[i - 1]][individual[i]]
    return distance,

toolbox.register("mate", tools.cxOrdered)
toolbox.register("mutate", tools.mutShuffleIndexes, indpb=0.05)
toolbox.register("select", tools.selTournament, tournsize=3)
toolbox.register("evaluate", evalTSP)

def main():
    random.seed(42)
    pop = toolbox.population(n=400)
    hof = tools.HallOfFame(1)
    stats = tools.Statistics(lambda ind: ind.fitness.values)
    stats.register("min", np.min)
    stats.register("avg", np.mean)

    algorithms.eaSimple(pop, toolbox, cxpb=0.7, mutpb=0.2, ngen=200, stats=stats, halloffame=hof, verbose=True)

    return pop, stats, hof

if __name__ == "__main__":
    pop, stats, hof = main()
    best_route = hof[0]
    print("Best route found:", best_route)
    print("Distance of the best route:", evalTSP(best_route)[0])

/usr/local/lib/python3.10/dist-packages/deap/creator.py:185: RuntimeWarning: A class named 'FitnessMin' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  warnings.warn("A class named '{0}' has already been created and it "
/usr/local/lib/python3.10/dist-packages/deap/creator.py:185: RuntimeWarning: A class named 'Individual' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  warnings.warn("A class named '{0}' has already been created and it "

gen	nevals	min   	avg
0  	400   	130.53	194.986
1  	323   	128.41	181.152
2  	302   	114.22	172.739
3  	298   	101.34	165.212
4  	305   	118.69	161.858
5  	295   	114.4 	156.385
6  	289   	103.6 	152.145
7  	307   	103.6 	149.49
8  	311   	103.6 	146.725
9  	302   	103.6 	146.165
10 	306   	101.34	144.026
11 	305   	101.34	142.975
12 	293   	101.34	139.157
13 	312   	101.34	137.046
14 	304   	101.34	133.648
15 	284   	101.34	129.37
16 	297   	101.34	127.168
17 	322   	101.34	124.988
18 	297   	101.34	121.15
19 	310   	101.34	119.657
20 	304   	101.34	116.706
21 	303   	101.34	120.905
22 	299   	101.34	119.232
23 	311   	101.34	117.013
24 	301   	101.34	116.332
25 	318   	101.34	116.166
26 	320   	101.34	115.459
27 	320   	101.34	113.801
28 	306   	101.34	113.485
29 	315   	101.34	110.973
30 	317   	101.34	108.094
31 	312   	101.34	105.512
32 	308   	101.34	104.952
33 	274   	101.34	104.662
34 	300   	101.34	104.752
35 	309   	101.34	106.661
36 	305   	101.34	104.433
37 	298   	101.34	104.618
38 	314   	101.34	104.198
39 	289   	101.34	105.732
40 	300   	101.34	104.209
41 	310   	101.34	105.969
42 	312   	101.34	104.146
43 	325   	101.34	103.842
44 	293   	101.34	104.765
45 	308   	101.34	104.897
46 	299   	101.34	104.608
47 	294   	101.34	105.4
48 	300   	101.34	103.849
49 	318   	101.34	104.707
50 	298   	101.34	105.193
51 	308   	101.34	106.899
52 	309   	101.34	105.361
53 	291   	101.34	104.668
54 	310   	101.34	104.955
55 	305   	101.34	104.822
56 	322   	101.34	104.928
57 	296   	101.34	106
58 	304   	101.34	105.156
59 	328   	101.34	105.414
60 	305   	101.34	105.2
61 	322   	101.34	104.892
62 	310   	101.34	105.413
63 	302   	101.34	104.986
64 	306   	101.34	105.535
65 	309   	101.34	106.579
66 	319   	101.34	105.76
67 	307   	101.34	104.155
68 	307   	101.34	105.469
69 	308   	101.34	104.765
70 	306   	101.34	103.877
71 	330   	101.34	105.75
72 	307   	101.34	104.906
73 	299   	101.34	103.734
74 	311   	101.34	104.202
75 	307   	101.34	104.177
76 	320   	101.34	105.153
77 	319   	101.34	104.488
78 	299   	101.34	105.493
79 	301   	101.34	104.563
80 	298   	101.34	104.038
81 	303   	101.34	105.084
82 	320   	101.34	105.524
83 	303   	101.34	105.641
84 	330   	101.34	105.942
85 	312   	101.34	105.086
86 	306   	101.34	105.931
87 	317   	101.34	103.636
88 	302   	101.34	102.977
89 	312   	101.34	104.702
90 	286   	101.34	105.558
91 	284   	101.34	104.365
92 	295   	101.34	104.821
93 	297   	101.34	104.019
94 	318   	101.34	105.306
95 	301   	101.34	104.965
96 	304   	101.34	104.299
97 	309   	101.34	104.183
98 	303   	101.34	104.796
99 	318   	101.34	104.447
100	313   	101.34	104.791
101	291   	101.34	103.662
102	292   	101.34	104.296
103	279   	101.34	104.836
104	288   	101.34	104.575
105	307   	101.34	105.184
106	311   	101.34	105.936
107	317   	101.34	105.879
108	282   	101.34	104.147
109	298   	101.34	104.554
110	297   	101.34	105.583
111	278   	101.34	104.093
112	280   	101.34	103.677
113	302   	101.34	105.656
114	313   	101.34	103.548
115	288   	101.34	104.955
116	311   	101.34	105.925
117	311   	101.34	104.741
118	308   	101.34	103.686
119	289   	101.34	104.134
120	323   	101.34	103.928
121	304   	101.34	103.47
122	292   	101.34	104.783
123	302   	101.34	105.014
124	299   	101.34	104.196
125	325   	101.34	105.446
126	304   	101.34	105.257
127	277   	101.34	103.57
128	312   	101.34	104.944
129	320   	101.34	105.363
130	308   	101.34	105.89
131	308   	101.34	105.195
132	301   	101.34	104.682
133	303   	101.34	105
134	293   	101.34	105.277
135	323   	101.34	105.777
136	291   	101.34	105.687
137	297   	101.34	104.907
138	313   	101.34	104.902
139	294   	101.34	103.942
140	318   	101.34	103.896
141	278   	101.34	104.79
142	298   	101.34	105.099
143	300   	101.34	104.336
144	315   	101.34	105.36
145	300   	101.34	105.479
146	284   	101.34	104.544
147	326   	101.34	104.855
148	336   	101.34	104.971
149	297   	101.34	104.637
150	321   	101.34	104.488
151	299   	101.34	103.782
152	315   	101.34	103.962
153	280   	101.34	103.668
154	299   	101.34	105.69
155	302   	101.34	105.381
156	306   	101.34	105.225
157	305   	101.34	104.834
158	293   	101.34	104.625
159	291   	101.34	106.212
160	300   	101.34	104.86
161	312   	101.34	105.54
162	302   	101.34	103.77
163	294   	101.34	105.098
164	299   	101.34	104.291
165	298   	101.34	105.4
166	292   	101.34	104.442
167	302   	101.34	104.222
168	319   	101.34	104.684
169	304   	101.34	104.641
170	317   	101.34	104.125
171	313   	101.34	103.845
172	304   	101.34	106.436
173	295   	101.34	105.455
174	305   	101.34	104.556
175	301   	101.34	105.285
176	297   	101.34	104.391
177	296   	101.34	104.269
178	307   	101.34	104.519
179	313   	101.34	103.695
180	294   	101.34	104.126
181	311   	101.34	104.168
182	302   	101.34	105.187
183	282   	101.34	104.903
184	311   	101.34	106.316
185	313   	101.34	104.098
186	309   	101.34	105.117
187	312   	101.34	104.921
188	316   	101.34	105.387
189	299   	101.34	105.101
190	298   	101.34	104.507
191	289   	101.34	104.746
192	313   	101.34	104.828
193	297   	101.34	104.892
194	284   	101.34	104.8
195	313   	101.34	104.838
196	325   	101.34	104.673
197	297   	101.34	103.809
198	307   	101.34	104.559
199	302   	101.34	104.425
200	312   	101.34	105.492
Best route found: [6, 4, 9, 3, 5, 8, 1, 7, 2, 0]
Distance of the best route: 101.33999999999999

In [ ]:
import random
import numpy as np
from deap import base, creator, tools, algorithms

# Distance matrix as a NumPy array
distance_matrix = np.array([
    [0, 18.56, 18.27, 18.89, 27.02, 18.72, 5.03, 23.32, 17.33, 17.83],
    [18.56, 0, 21.16, 22.32, 31.64, 26.57, 21.11, 12.62, 9.85, 22.46],
    [18.27, 21.16, 0, 33.11, 20.42, 18.94, 25.32, 5.46, 16.88, 24.9],
    [18.89, 22.32, 33.11, 0, 28.73, 17.59, 23.77, 22.48, 27.82, 8.87],
    [27.02, 31.64, 20.42, 28.73, 0, 25.68, 5, 5, 13.93, 10.84],
    [18.72, 26.57, 18.94, 17.59, 25.68, 0, 28.76, 26.64, 7.81, 28.47],
    [5.03, 21.11, 25.32, 23.77, 5, 28.76, 0, 9.98, 19.14, 17.06],
    [23.32, 12.62, 5.46, 22.48, 5, 26.64, 9.98, 0, 21.14, 28.19],
    [17.33, 9.85, 16.88, 27.82, 13.93, 7.81, 19.14, 21.14, 0, 26.38],
    [17.83, 22.46, 24.9, 8.87, 10.84, 28.47, 17.06, 28.19, 26.38, 0]
])

# Number of cities
num_cities = len(distance_matrix)

# Specify the starting city (e.g., 'A' is index 0)
start_idx = 0

# Create the fitness function and individual class
creator.create("FitnessMin", base.Fitness, weights=(-1.0,))
creator.create("Individual", list, fitness=creator.FitnessMin)

# Initialize the toolbox
toolbox = base.Toolbox()

# Attribute generator: random permutation of cities excluding the starting city
def random_permutation():
    return random.sample([i for i in range(num_cities) if i != start_idx], num_cities - 1)

toolbox.register("indices", random_permutation)

# Structure initializers
toolbox.register("individual", tools.initIterate, creator.Individual, toolbox.indices)
toolbox.register("population", tools.initRepeat, list, toolbox.individual)

# Evaluation function
def evalTSP(individual):
    # Add the starting city at the beginning and end of the route
    route = [start_idx] + individual + [start_idx]
    distance = 0
    for i in range(len(route) - 1):
        distance += distance_matrix[route[i]][route[i + 1]]
    return distance,

# Custom crossover function to handle the fixed starting city
def fixed_start_crossover(ind1, ind2):
    size = len(ind1)
    start, end = sorted(random.sample(range(size), 2))
    child1 = [-1] * size
    child2 = [-1] * size

    # Copy crossover segment from first parent
    child1[start:end] = ind1[start:end]
    child2[start:end] = ind2[start:end]

    # Fill the rest from the other parent
    remaining1 = [gene for gene in ind2 if gene not in child1]
    remaining2 = [gene for gene in ind1 if gene not in child2]

    pointer1, pointer2 = 0, 0
    for i in range(size):
        if child1[i] == -1:
            child1[i] = remaining1[pointer1]
            pointer1 += 1
        if child2[i] == -1:
            child2[i] = remaining2[pointer2]
            pointer2 += 1

    return creator.Individual(child1), creator.Individual(child2)

toolbox.register("mate", fixed_start_crossover)
toolbox.register("mutate", tools.mutShuffleIndexes, indpb=0.05)
toolbox.register("select", tools.selTournament, tournsize=3)
toolbox.register("evaluate", evalTSP)

def main():
    # Seed for reproducibility
    random.seed(42)

    # Initialize the population
    pop = toolbox.population(n=400)
    hof = tools.HallOfFame(1)
    stats = tools.Statistics(lambda ind: ind.fitness.values)
    stats.register("min", np.min)
    stats.register("avg", np.mean)

    # Run the genetic algorithm
    algorithms.eaSimple(
        pop,
        toolbox,
        cxpb=0.7,
        mutpb=0.2,
        ngen=200,
        stats=stats,
        halloffame=hof,
        verbose=True
    )

    # Return the population, statistics, and the Hall of Fame
    return pop, stats, hof

if __name__ == "__main__":
    pop, stats, hof = main()
    best_route = hof[0]

    print("Best route found (indices):", [start_idx] + best_route + [start_idx])
    print("Distance of the best route:", evalTSP(best_route)[0])

gen	nevals	min   	avg
0  	400   	136.36	195.285
1  	300   	128.82	181.651
2  	295   	116.58	173.183
3  	312   	116.58	167.364
4  	310   	112.84	160.358
5  	300   	101.34	153.099
6  	299   	101.34	150.704
7  	299   	101.34	142.931
8  	330   	101.34	137.628
9  	291   	101.34	130.814
10 	305   	101.34	125.423
11 	314   	101.34	120.041
12 	300   	101.34	116.665
13 	302   	101.34	112.402
14 	317   	101.34	106.849
15 	295   	101.34	104.369
16 	318   	101.34	103.986
17 	321   	101.34	105.537
18 	306   	101.34	104.087
19 	303   	101.34	104.754
20 	286   	101.34	104.123
21 	300   	101.34	104.418
22 	310   	101.34	105.169
23 	303   	101.34	104.272
24 	296   	101.34	105.34
25 	298   	101.34	105.444
26 	312   	101.34	105.442
27 	314   	101.34	105.002
28 	313   	101.34	104.672
29 	314   	101.34	105.53
30 	288   	101.34	105.265
31 	316   	101.34	104.79
32 	301   	101.34	104.337
33 	315   	101.34	104.444
34 	303   	101.34	104.309
35 	299   	101.34	104.717
36 	312   	101.34	104.807
37 	304   	101.34	104.376
38 	308   	101.34	104.51
39 	284   	101.34	104.055
40 	296   	101.34	104.962
41 	314   	101.34	104.543
42 	321   	101.34	104.049
43 	294   	101.34	104.63
44 	298   	101.34	104.671
45 	308   	101.34	105.051
46 	298   	101.34	104.569
47 	308   	101.34	104.114
48 	316   	101.34	105.476
49 	299   	101.34	104.638
50 	309   	101.34	104.622
51 	304   	101.34	103.753
52 	309   	101.34	104.652
53 	304   	101.34	104.984
54 	298   	101.34	104.738
55 	309   	101.34	104.808
56 	310   	101.34	104.597
57 	296   	101.34	103.661
58 	325   	101.34	104.796
59 	283   	101.34	104.411
60 	291   	101.34	105.179
61 	312   	101.34	104.357
62 	313   	101.34	104.46
63 	315   	101.34	105.161
64 	329   	101.34	105.637
65 	308   	101.34	105.316
66 	279   	101.34	104.691
67 	301   	101.34	106.11
68 	299   	101.34	104.229
69 	280   	101.34	103.179
70 	319   	101.34	105.119
71 	305   	101.34	103.233
72 	310   	101.34	104.858
73 	289   	101.34	104.846
74 	309   	101.34	105.13
75 	306   	101.34	104.454
76 	317   	101.34	104.72
77 	291   	101.34	103.755
78 	306   	101.34	105.208
79 	306   	101.34	105.627
80 	324   	101.34	106.194
81 	300   	101.34	104.211
82 	301   	101.34	102.942
83 	299   	101.34	105.185
84 	305   	101.34	104.765
85 	309   	101.34	104.525
86 	299   	101.34	104.968
87 	308   	101.34	104.745
88 	307   	101.34	103.987
89 	326   	101.34	104.825
90 	317   	101.34	104.627
91 	331   	101.34	104.011
92 	312   	101.34	104.621
93 	301   	101.34	105.064
94 	291   	101.34	104.291
95 	305   	101.34	104.056
96 	308   	101.34	104.842
97 	293   	101.34	105.107
98 	297   	101.34	105.354
99 	284   	101.34	104.964
100	309   	101.34	104.302
101	293   	101.34	103.657
102	308   	101.34	104.437
103	316   	101.34	105.759
104	309   	101.34	104.358
105	303   	101.34	104.234
106	319   	101.34	105.359
107	307   	101.34	104.134
108	305   	101.34	104.333
109	307   	101.34	105.679
110	312   	101.34	105.886
111	293   	101.34	105.252
112	305   	101.34	105.024
113	299   	101.34	104.833
114	290   	101.34	105.137
115	297   	101.34	105.16
116	322   	101.34	103.759
117	308   	101.34	104.593
118	336   	101.34	104.173
119	286   	101.34	104.379
120	337   	101.34	104.688
121	319   	101.34	104.404
122	296   	101.34	104.327
123	301   	101.34	103.548
124	290   	101.34	104.722
125	302   	101.34	104.303
126	301   	101.34	104.398
127	301   	101.34	105.066
128	299   	101.34	104.771
129	307   	101.34	104.601
130	296   	101.34	104.05
131	298   	101.34	105.36
132	301   	101.34	105.136
133	294   	101.34	105.328
134	321   	101.34	104.802
135	302   	101.34	104.089
136	307   	101.34	105.106
137	302   	101.34	105.04
138	298   	101.34	105.185
139	308   	101.34	104.863
140	288   	101.34	104.647
141	303   	101.34	104.253
142	317   	101.34	104.157
143	326   	101.34	104.388
144	301   	101.34	103.69
145	292   	101.34	105.279
146	293   	101.34	104.055
147	330   	101.34	105.974
148	304   	101.34	104.541
149	305   	101.34	104.507
150	313   	101.34	105.05
151	309   	101.34	105.05
152	311   	101.34	104.465
153	314   	101.34	103.888
154	301   	101.34	104.062
155	298   	101.34	104.195
156	306   	101.34	104.511
157	286   	101.34	104.884
158	309   	101.34	104.676
159	312   	101.34	104.58
160	311   	101.34	104.446
161	308   	101.34	104.761
162	314   	101.34	104.489
163	323   	101.34	104.158
164	300   	101.34	104.756
165	312   	101.34	104.69
166	312   	101.34	105.595
167	305   	101.34	104.104
168	317   	101.34	104.863
169	312   	101.34	104.857
170	313   	101.34	103.622
171	306   	101.34	104.295
172	314   	101.34	103.892
173	273   	101.34	104.257
174	265   	101.34	103.657
175	310   	101.34	105.104
176	292   	101.34	104.627
177	292   	101.34	104.827
178	304   	101.34	105.247
179	308   	101.34	104.474
180	297   	101.34	104.598
181	305   	101.34	105.086
182	322   	101.34	104.767
183	296   	101.34	104.202
184	303   	101.34	104.355
185	310   	101.34	103.829
186	318   	101.34	104.657
187	318   	101.34	104.949
188	306   	101.34	106.101
189	308   	101.34	104.868
190	302   	101.34	104.716
191	313   	101.34	104.935
192	335   	101.34	105.103
193	303   	101.34	104.881
194	301   	101.34	105.378
195	296   	101.34	105.233
196	297   	101.34	104.6
197	309   	101.34	104.55
198	282   	101.34	104.89
199	305   	101.34	105.135
200	333   	101.34	104.275
Best route found (indices): [0, 6, 4, 9, 3, 5, 8, 1, 7, 2, 0]
Distance of the best route: 101.33999999999999

In [ ]:
import pandas as pd

def run_algorithm():
    random.seed(42)
    pop = toolbox.population(n=400)
    hof = tools.HallOfFame(1)
    stats = tools.Statistics(lambda ind: ind.fitness.values)
    stats.register("min", np.min)
    stats.register("avg", np.mean)

    algorithms.eaSimple(pop, toolbox, cxpb=0.7, mutpb=0.2, ngen=200, stats=stats, halloffame=hof, verbose=False)
    return evalTSP(hof[0])[0]  # Return the best distance

results = [run_algorithm() for _ in range(100)]
df = pd.DataFrame(results, columns=["Best Distance"])
pd.options.display.float_format = '{:.2f}'.format
df.describe()

df = pd.DataFrame(results, columns=["Best Distance"])
pd.options.display.float_format = '{:.2f}'.format
df.describe()

       Best Distance
count         100.00
mean          101.34
std             0.00
min           101.34
25%           101.34
50%           101.34
75%           101.34
max           101.34